#ifndef FSFW_DEFAULTCFG_VERSION_H_
#define FSFW_DEFAULTCFG_VERSION_H_

const char* const FSFW_VERSION_NAME = "ASTP";

#define FSFW_VERSION 		0
#define	FSFW_SUBVERSION 	0
#define	FSFW_REVISION 	1



#endif /* FSFW_DEFAULTCFG_VERSION_H_ */
