/**
 * @file	ServiceTypes.h
 * @brief	This file defines the ServiceTypes class.
 * @date	11.04.2013
 * @author	baetz
 */

#ifndef SERVICETYPES_H_
#define SERVICETYPES_H_

namespace SERVICE {
enum ServiceTypes {
	TELECOMMAND_VERIFICATION = 1,
	DEVICE_COMMAND_DISTRIBUTION = 2,
	HOUSEKEEPING_AND_DIAGNOSTIC_DATA_REPORTING = 3,
	PARAMETER_STATISTICS_REPORTING = 4,
	EVENT_REPORTING = 5,
	MEMORY_MANAGEMENT = 6,
	FUNCTION_MANAGEMENT = 8,
	TIME_MANAGEMENT = 9,
	ON_BOARD_OPERATIONS_SCHEDULING = 11,
	ON_BOARD_MONITORING = 12,
	LARGE_DATA_TRANSFER = 13,
	PACKET_FORWARDING_CONTROL = 14,
	ON_BOARD_STORAGE_AND_RETRIEVAL = 15,
	TEST = 17,
	ON_BOARD_OPERATIONS_PROCEDURE = 18,
	EVENT_ACTION = 19
};
}

#endif /* SERVICETYPES_H_ */
