#ifndef FSFW_EVENTS_FWSUBSYSTEMIDRANGES_H_
#define FSFW_EVENTS_FWSUBSYSTEMIDRANGES_H_

namespace SUBSYSTEM_ID {
enum {
	MEMORY = 22,
	OBSW = 26,
	CDH = 28,
	TCS_1 = 59,
	PCDU_1 = 42,
	PCDU_2 = 43,
	HEATER = 50,
	T_SENSORS = 52,
	FDIR = 70,
	FDIR_1 = 71,
	FDIR_2 = 72,
	HK = 73,
	SYSTEM_MANAGER = 74,
	SYSTEM_MANAGER_1 = 75,
	SYSTEM_1 = 79,
	PUS_SERVICE_1 = 80,
	PUS_SERVICE_9 = 89,
	PUS_SERVICE_17 = 97,
	FW_SUBSYSTEM_ID_RANGE
};
}



#endif /* FSFW_EVENTS_FWSUBSYSTEMIDRANGES_H_ */
